baseURL = 'https://hankamokra.cz/'
languageCode = 'cs'
title = 'Hanka Mokrá | Garant metody JIH®'
theme = 'hanka'

[params]
  description = 'Garant metody JIH® s 15letou zkušeností. Osobní vedení a vzdělávací cesta pro ženy 45–55 let, které už nechtějí čekat, ale chtějí konečně žít naplno.'

[[menu.main]]
  name = 'O mně'
  url = '/o-mne/'
  weight = 10

[[menu.main]]
  name = 'Metoda JIH'
  url = '/metoda-jih/'
  weight = 20

[[menu.main]]
  name = 'Osobní vedení'
  url = '/osobni-vedeni/'
  weight = 30

[[menu.main]]
  name = 'Blog'
  url = '/blog/'
  weight = 40

[[menu.main]]
  name = 'Spolupráce'
  url = '/spoluprace/'
  weight = 50

[[menu.main]]
  name = 'Kontakt'
  url = '/kontakt/'
  weight = 60
